version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: sca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: source_agent
      MYSQL_USER: dump
      MYSQL_PASSWORD: dump111
    ports:
      - "6006:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script/init-sql.sql:/docker-entrypoint-initdb.d/init-sql.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: sca-backend
    image: crpi-8rc8wfim7gn3al0b.cn-shanghai.personal.cr.aliyuncs.com/wlw-sca/chinamobiledemo-backend:v1.0.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+asyncmy://test_account%3Aadmin:test123@sca-matrixone:6001/xunyuan_agent
      LLM_API_KEY: sk-vbejswkfqhmfkslsfluyhhrlamxdhtzonsundldhjfjecfxi
      LLM_BASE_URL: http://localhost:8000
      LLM_DEFAULT_MODEL: qwen-turbo
      LLM_MAX_TOKENS: 4096
      LLM_TEMPERATURE: 0.7
      LLM_STREAM: true
      WEB_SEARCH_API_URL: ""
      WEB_SEARCH_API_KEY: ""
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sca-frontend
    image: crpi-8rc8wfim7gn3al0b.cn-shanghai.personal.cr.aliyuncs.com/wlw-sca/chinamobiledemo-frontend:v1.0.0
    depends_on:
      backend:
        condition: service_started
    environment:
      VITE_SILICONFLOW_API_KEY: sk-vbejswkfqhmfkslsfluyhhrlamxdhtzonsundldhjfjecfxi # 模型API密钥
      VITE_SILICONFLOW_BASE_URL: http://10.222.3.121:5178/ai # 模型地址
      VITE_API_BASE_URL: "http://10.222.3.121:5178" # 后端API地址 配置前端CONFIG
      # Nginx 代理配置
      BACKEND_HOST: 10.222.3.121 # 后端主机
      BACKEND_PORT: 8000 # 后端端口
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5178:80"

  cas:
    image: apereo/cas:7.0.0
    container_name: sca-cas
    ports:
      - "8080:8080"
    environment:
      CAS_SERVER_NAME: "http://localhost:8080"
      CAS_SERVER_PREFIX: "/cas"
      SERVER_SSL_ENABLED: "false"
      SPRING_PROFILES_ACTIVE: "standalone"
    volumes:
      - ./cas/config:/etc/cas/config
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/cas/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  db_data:

