version: "3.9"

services:
  db:
    image: matrixorigin/matrixone:3.0.4-hotfix-20251213
    container_name: sca-matrixone
    environment:
      # 启用实验性向量索引功能
      MO_ENABLE_EXPERIMENTAL_IVF_INDEX: "true"
    ports:
      - "6001:6001"
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/6001' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: sca-backend
    image: crpi-8rc8wfim7gn3al0b.cn-shanghai.personal.cr.aliyuncs.com/wlw-sca/chinamobiledemo-backend:v1.0.0-0179e1e7-2025-12-29
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+asyncmy://test_account%3Aadmin:test123@sca-matrixone:6001/xunyuan_agent
      LLM_API_KEY: sk-vbejswkfqhmfkslsfluyhhrlamxdhtzonsundldhjfjecfxi
      LLM_BASE_URL: http://localhost:8000
      LLM_DEFAULT_MODEL: qwen-turbo
      LLM_MAX_TOKENS: 4096
      LLM_TEMPERATURE: 0.7
      LLM_STREAM: true
      WEB_SEARCH_API_URL: ""
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sca-frontend
    image: crpi-8rc8wfim7gn3al0b.cn-shanghai.personal.cr.aliyuncs.com/wlw-sca/chinamobiledemo-frontend:v1.0.0
    depends_on:
      backend:
        condition: service_started
    environment:
      VITE_SILICONFLOW_API_KEY: sk-vbejswkfqhmfkslsfluyhhrlamxdhtzonsundldhjfjecfxi # 模型API密钥
      VITE_SILICONFLOW_BASE_URL: http://localhost:8000 # 模型地址
      VITE_API_BASE_URL: "http://localhost:8000" # 后端API地址 配置前端CONFIG
      # Nginx 代理配置
      BACKEND_HOST: backend # 后端主机
      BACKEND_PORT: 8000 # 后端端口
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5178:80"


